const devices={router1:{name:'Rabit CPE XR',ip:'192.168.100.1',user:'admin',pass:'admin'},router2:{name:'FiberHome HG6145D2',ip:'192.168.100.2',user:'admin',pass:'%0|F?H@f!berhO3e'}};
const $=s=>document.querySelector(s);const toast=$('#toast');let deferredPrompt;
function credentials(){try{return JSON.parse(localStorage.getItem('wifiCtrlCredentials'))||Object.fromEntries(Object.entries(devices).map(([k,d])=>[k,{user:d.user,pass:d.pass}]))}catch{return Object.fromEntries(Object.entries(devices).map(([k,d])=>[k,{user:d.user,pass:d.pass}]))}}
function notify(msg='Copied to clipboard'){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
async function copy(value){if(!value){notify('Belum diisi');return}try{await navigator.clipboard.writeText(value);notify()}catch{notify('Copy tidak tersedia')}}
function renderVault(){const data=credentials();$('#credentialList').innerHTML=Object.entries(devices).map(([key,d])=>`<div class="credential"><div class="credential-name">${d.name}</div><label>Username</label><div class="credential-value"><span>${data[key].user||'Not configured'}</span><button data-value="${data[key].user||''}">copy</button></div><label style="margin-top:13px">Password</label><div class="credential-value"><span>${data[key].pass||'Not configured'}</span><button data-value="${data[key].pass||''}">copy</button></div></div>`).join('');$('#credentialList').querySelectorAll('button').forEach(b=>b.onclick=()=>copy(b.dataset.value))}
function renderForm(){const data=credentials();$('#formFields').innerHTML=Object.entries(devices).map(([key,d])=>`<div class="credential"><div class="credential-name">${d.name} <small>${d.ip}</small></div><div class="field"><label>Username</label><input name="${key}-user" value="${data[key].user||''}" autocomplete="off"></div><div class="field"><label>Password</label><input name="${key}-pass" type="text" value="${data[key].pass||''}" autocomplete="off"></div></div>`).join('')}
$('#vaultBtn').onclick=()=>{$('#vaultDialog').showModal();renderVault()};$('#settingsBtn').onclick=()=>{$('#settingsDialog').showModal();renderForm()};$('#editCredentials').onclick=()=>{$('#vaultDialog').close();$('#settingsDialog').showModal();renderForm()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copy(b.dataset.copy));$('#credentialForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),out={};Object.keys(devices).forEach(k=>out[k]={user:f.get(`${k}-user`),pass:f.get(`${k}-pass`)});localStorage.setItem('wifiCtrlCredentials',JSON.stringify(out));$('#settingsDialog').close();notify('Saved locally')};
function clock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})+' LOCAL TIME'}clock();setInterval(clock,1000);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
